### ISSUE TITLE
I have bedmethyl file, How can I find the cpg name for each position?

### ISSUE THREAD

**Issue by ralanany** [nanoporetech/modkit#326] opened 2024-12-29 05:54 UTC
I have the bedmethyl file with chr no, chr position and modification. But the cpg name not mentioned. I want help to find the cpg name as below

cg13869341 chr1 [15865, 15865] 
cg14008030 chr1 [18827, 18827] 
cg12045430 chr1 [29407, 29407]

**Comment by ArtRand** [comment] 2024-12-30 18:37
Looks like this is a duplicate of #317.

**Closed by ArtRand** 2024-12-30 18:37 UTC
