### ISSUE TITLE
Adjust-mods unexpected behaviour.

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/modkit#79] opened 2023-11-08 11:25 UTC
The documentation  for adjust-mods states:

> Combining base modification probabilities may be desirable for downstream analysis or visualization. Unlike --ignore which removes the probability of a class, --convert will sum the probability of one class with another if the second class already exists. For example, the command below will convert probabilities associated with h probability into m probability. If m already exists, the probabilities will be summed. As described in [changing the modification code](https://nanoporetech.github.io/modkit/intro_adjust.html#changing-the-base-modification-code), if the second base modification code doesn't exist, the probabilities are left unchanged.

> `modkit adjust-mods input.bam output.convert.bam --convert h m`
This would be equivalent to setting --combine-mods flag, for example.
`modkit pileup path/to/reads.bam output/path/pileup.bed --combine-mods`

https://nanoporetech.github.io/modkit/intro_adjust.html#combining-base-modification-probabilities

The docs do not specify how alignments (specifically secondary and supplemntary) are handled in this process, but we've noticed they are removed.

I assumed that all alignment data would be preserved in a BAM file if adjust-mods is used but this appears to be incorrect.

**Comment by ArtRand** [comment] 2023-11-08 14:56
Hello @mattloose,

That's correct, only primary alignments will be emitted. The  [extract](https://nanoporetech.github.io/modkit/intro_extract.html#extracting-base-modification-information) section documents the behavior, but all of the commands that are "BAM-in, BAM-out" should have this message. 

I'd actually like to remove this limitation. I can imagine a couple ways. The problem is that secondary/supplementary alignments have empty/* SEQ fields, making decoding the MM tags impossible. I appreciate that you could still adjust the probabilities, but the mechanism internal to `modkit` will basically ignore them (I believe pysam won't even give you the probabilities for secondary records). 

Some potential solutions:
1. Emit the secondary/supplementary alignments with the MM/ML tags removed, you should get a BAM with the same number of records. 
2. Allow certain manipulations to happen in non-primary alignments, such as probability arithmetic.
3. Attempt to leverage the `cs` tag optionally added by [minimap](https://lh3.github.io/minimap2/minimap2.html) to decode the sequence for the read. 

I don't know if (1) is of any use, but I think (2) and (3) would be with the appropriate documentation and warnings. How would these effect your use case? 

I also noticed that:


>   modkit adjust-mods input.bam output.convert.bam --convert h m
    This would be equivalent to setting --combine-mods flag, for example.
    modkit pileup path/to/reads.bam output/path/pileup.bed --combine-mods

isn't technically correct, I'll update the language.

**Comment by mattloose** [comment] 2023-11-08 15:08
OK - I never would have looked under the extract command to understand the behaviour of the adjust-mods command!

The explanation is helpful but the impact requires some thought on my part. 

The question is what are the downstream tools expecting when handling the methylation information and are those tools aware that secondary/supplementary alignments can't decode the MM tags (this isn't a mod-kit problem of course). For my use case, I would ignore secondary reads but would seek to analyse methylation in supplementary alignments.

It seems to me this issue is bigger than just modkit!

**Comment by ArtRand** [comment] 2023-12-04 16:42
Hello @mattloose 
I've updated the [documentation](https://nanoporetech.github.io/modkit/intro_adjust.html) to include mention that non-primary alignments will not be in the output. I have it on the roadmap to augment the `update-tags` command so that it will make supplementary and secondary alignments "valid" with respect to their MM/ML tags. Feel free to open another issue to track that work if you like.

**Comment by ArtRand** [comment] 2023-12-27 22:07
Hello @mattloose 

As of [v0.2.4](https://github.com/nanoporetech/modkit/releases/tag/v0.2.4) you can get secondary and supplementary alignment information with `modkit adjust-mods` so long as the MN tag is correct. You can find information on how to make sure your alignments have a correct MN tag in the [troubleshooting docs](https://nanoporetech.github.io/modkit/troubleshooting.html#missing-secondary-and-supplementary-alignments-in-output).

**Comment by ArtRand** [comment] 2024-01-08 15:09
@mattloose I'm going to close this issue as completed, but please re-open it if you cannot get non-primary alignments in `adjust-mods` output. Thanks.

**Closed** 2024-01-08 15:09 UTC
Labels: documentation
