### ISSUE TITLE
pileup-hemi input

### ISSUE THREAD

**Issue by pkharchenko** [nanoporetech/modkit#57] opened 2023-09-27 04:05 UTC
Dear Modkit Developers,

Excited to see the new pileup-hemi function! I can't quite figure out how to produce the required bam input file. Looking at the duplex_modbam.bam example in the tests/resources, it seems similar to dorado duplex output, but also contains modification tags (which dorado can currently output only with plain basecaller command, but not with duplex). Hoping you can point me in the right direction.

Thanks in advance!

**Comment by ArtRand** [comment] 2023-09-28 13:36
Hello @pkharchenko,

Currently the workflow is a little complicated, but I'll list out the general steps below. The dorado team is [actively developing](https://github.com/nanoporetech/dorado/issues/329) a more streamlined version of duplex modified base calling that will reduce the workflow to a single step. 

To generate pileup-hemi input data you need duplex reads with modified base calls on the top and bottom strands. Currently, the only way to perform this modified base calling is with [remora](https://github.com/nanoporetech/remora) using the `remora infer duplex_from_pod5_and_bam`, I've reproduced the input requirements below:

```
  pod5                  POD5 file corresponding to bam file.
  simplex_bam           Base called BAM file containing mv tags.
  duplex_bam            BAM file containing duplex base called sequences (and optional reference mappings). Record names may either be the template read_id or template<delim>complement. The value of <delim>
                        can be set with --duplex-delim.
  duplex_read_pairs     Whitespace separated plain text file containing read ID pairs, no header.
```

The pod5 is the same pod5 you use for basecalling normally, I like to have just one large pod5 with everything. Keep in mind that in remora2 you cannot use a directory of pod5s like dorado can - this limitation will be removed soon. The `simplex_bam` is the unaligned BAM (uBAM) **with moves** you can get this file using the `dorado basecaller` with `--emit-moves`. The `duplex_bam` is the BAM (mapped or unmapped) from `dorado duplex`, you will need to filter this BAM to only duplex records with `dx:i:1` tags (`samtools view -bh -d dx:1 ${duplex_bam}` will do it). To generate the `duplex_read_pairs` this command will do: 
```
samtools view -d dx:1 ${duplex_bam} | cut -f 1 | awk -F=";" 'BEGIN{FS=";"; OFS=" "}{print $1, $2}' | sort | uniq
```

Finally pick the remora model you want (SUP or HAC will do) and set the program to run. 

As I say, this will become a lot easier soon, but thanks for being willing to try something on the cutting edge! Please let me know if you encounter any problems.

**Comment by getopt** [comment] 2023-10-16 22:53
hello @ArtRand 

Thank you for outlining steps required to prepare input data for modkit pileup-hemi with remora. It's great to be able to start using it. 

I noticed that remora basecalling on A100 seems to be more than five times slower than either simplex or duplex dorado basecalling. Do you have any suggestions or tips that can help to get through the remora step faster?

**Comment by ArtRand** [comment] 2023-10-17 00:26
Hello @getopt,

Unfortunately, I don't have any real suggestions on how to speed up the remora step. I know it's slow, but the dorado version should be a lot quicker. Let me circle up internally and get back with a short and medium-term solution.

**Comment by getopt** [comment] 2023-10-25 20:43
Hello @ArtRand 

I wonder if you have any updates on any short and medium-term solutions for getting through the remora step faster?

In the mean time, I was experimenting with different ways of running remora and I would appreciate if you can comment on two observations that I made:

1. Looking at iterations per second that are printed when the program is running and the rate with which output mod bam file is written out, `remora` seems to be about 1.5x - 1.6x faster when it runs on 30% - 40% subset of P2 HD flow cell (that is starting from matching duplex read pair ids, merged.pod5 file, simplex and duplex bam files that correspond to about 30% of channels on a flow cell) in comparison to when running remora on 100% of data from a flow cell. 
2. When starting remora on BAM file with duplex basecalls with alignments, it does not make a difference for speed or resulting mod bam output whether I use simplex bam with mods, moves and alignments, or with moves and mods, but no alignments. 

Thank you

**Comment by marcus1487** [comment] 2023-10-26 22:37
The next release of Remora will have some optimizations for simplex inference. We have not completed this optimization for duplex calling, but it is on the roadmap. The main bottleneck is likely file access, so as you've found working on smaller subsets and working from faster random access disk are likely the best workarounds for now. This is also on the roadmap for inclusion in dorado (direct duplex modified base calling), which will be the recommendation in the long term.

**Comment by ArtRand** [comment] 2023-12-15 14:23
Hello @getopt  and @pkharchenko,

As of 0.5.0 [dorado duplex](https://github.com/nanoporetech/dorado/#duplex) has base modification support that can be used as input for `modkit pileup-hemi`. Feel free to re-open or make a new issue if you have any questions.

**Closed by ArtRand** 2023-12-15 14:23 UTC
